services:

  okta-mcp-server-gateway:
    image: okta-mcp-server-gateway:latest
    build:
      context: .
      dockerfile: Dockerfile-gateway
    pull_policy: never
    environment:
      - OKTA_ORG_URL=${OKTA_ORG_URL}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - OKTA_KEY_ID=${OKTA_KEY_ID}
      - OKTA_PRIVATE_KEY=${OKTA_PRIVATE_KEY}
      - OKTA_SCOPES=${OKTA_SCOPES:-okta.users.read}
      - OKTA_LOG_LEVEL=${OKTA_LOG_LEVEL:-INFO}
      - GATEWAY_LOG_LEVEL=${GATEWAY_LOG_LEVEL:-info}
    volumes:
      - ./data/okta-mcp/logs:/app/logs:rw
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - "8000:8000"

  gemini-cli:
    image: us-docker.pkg.dev/gemini-code-dev/gemini-cli/${GEMINI_CLI_VERSION:-sandbox:0.7.0}
    volumes:
    - ./data/gemini/:/home/node/.gemini/:rw
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NODE_ENV=${GEMINI_ENV:-production}
    user: "1000:1000"
    depends_on:
      okta-mcp-server-gateway:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: ["tail -f /dev/null"]
    platform: linux/amd64 # Workaround for compatibility with MacOS
    restart: unless-stopped
    working_dir: /home/gemini

networks:
  default:
    name: okta-mcp-lab-network
    driver: bridge
